### ISSUE TITLE
what

### ISSUE THREAD

**Issue by calebrwalk5** [Itz-Hyperz/firewallgg#53]
what the hell is the point of using github if you're gonna post a program that uses a damn proprietary API???

**Comment by Itz-Hyperz** [comment]
for public contribution you idiot

**Comment by calebrwalk5** [comment]
> for public contribution you idiot

>:(

**Comment by Itz-Hyperz** [comment]
somebody didn't do their research
![email](https://cdn.hyperz.net/u/main/bx0tb7c.png)

**Comment by Chris-Newton2000** [comment]
💀
